### ISSUE TITLE
beforeFeature() should not run on not selected features

### ISSUE THREAD

**Issue by agajdosi** [DATA-DOG/godog#104]
Hi, I have implemented before- and afterFeature() hooks into our tests, they serve us well, thank you for addition. However one minor thing I have realized is that they are being run even on those features, which were not selected by tag. As there are only clean-ups in my case, everything is alright, but it slows the execution of tests a little bit and on bigger projects this could be a more serious issue.

Also it messes my log and so I am going for adding an if check for tags in beforeFeature(), however if this functionality was out of the box from Godog, that would be nice I think.

**Comment by l3pp4rd** [comment]
Hi, yes should be fixed in the near future, thanks for reporting that

**Comment by agajdosi** [comment]
@l3pp4rd Thanks for information. I can help if you will be short on time.

Just realized a small thing related to this issue, would be nice if beforeFeature() was run after the Feature header is printed, so the warning messages are graphically part of the Feature block.

Situation now:
```gherkin
Feature: Version command
  Command "minishift version" shows version of minishift binary.

  Scenario: User can get information about version of Minishift                  # features/cmd-version.feature:5
    When executing "minishift version" succeeds                                  # integration_test.go:724 -> executingMinishiftCommandSucceedsOrFails
    Then stdout should match "^minishift v[0-9]\.[0-9]\.[0-9]\+[a-z0-9]{7,8}\n$" # integration_test.go:702 -> commandReturnShouldMatchRegex

Command ssh -- ls returned non-zero exit code: 1, StdOut: , StdErr: Command failed: Machine 'minishift' does not exist. You need to run 'minishift start' first

Feature: Cool Store
  In order to test Minishift under load
  I need to setup a test environment
  Using CentOS and 4G of memory
  
  Scenario: Starting                 # features/coolstore.feature:9
``` 

Proposed:
```gherkin
Feature: Version command
  Command "minishift version" shows version of minishift binary.

  Scenario: User can get information about version of Minishift                  # features/cmd-version.feature:5
    When executing "minishift version" succeeds                                  # integration_test.go:724 -> executingMinishiftCommandSucceedsOrFails
    Then stdout should match "^minishift v[0-9]\.[0-9]\.[0-9]\+[a-z0-9]{7,8}\n$" # integration_test.go:702 -> commandReturnShouldMatchRegex

Feature: Cool Store
  In order to test Minishift under load
  I need to setup a test environment
  Using CentOS and 4G of memory

Command ssh -- ls returned non-zero exit code: 1, StdOut: , StdErr: Command failed: Machine 'minishift' does not exist. You need to run 'minishift start' first

  Scenario: Starting                 # features/coolstore.feature:9
```
This would make console output more readable.

**Comment by l3pp4rd** [comment]
Hm, this is interesting actually. Basically we have two options.
when we run an empty feature with `pretty` format

1. we can still print it, even though there are no scenarios.
2. we simply exclude all the features, if there are no scenarios there.

But in that case, there might be empty scenarios defined like:

``` gherkin
Feature: maybe feature

  Scenario: one

  Scenario: two
```

Which does not make sense to setup database for example before such a feature, but those scenarios are just pending definition. And it also make sense to print them when running with `pretty` format (currently needs to be fixed, does not print empty scenarios). But this is valid gherkin and must be properly processed.

So in my opinion, it still makes sense to fire this event, since we actually have a physical feature defined. But you user should check on his own, whether the feature or scenario is empty. Since godog passes the gherkin object to each of the event hooks.

So you could for example have something like this:

``` go
package main

import (
	"fmt"

	"github.com/DATA-DOG/godog"
	"github.com/DATA-DOG/godog/gherkin"
)

func FeatureContext(s *godog.Suite) {
	s.Step(`^passing$`, func() error {
		return nil
	})

	s.BeforeFeature(func(ft *gherkin.Feature) {
		if len(ft.ScenarioDefinitions) > 0 {
			fmt.Println("EVENT BEFORE FEATURE:", ft.Name)
		}
	})

	s.BeforeScenario(func(s interface{}) {
		var steps int
		var name string
		switch t := s.(type) {
		case *gherkin.Scenario:
			steps = len(t.Steps)
			steps = len(t.Steps)
			name = t.Name
		case *gherkin.ScenarioOutline:
			steps = len(t.Steps)
			steps = len(t.Steps)
			name = t.Name
		}

		if steps > 0 {
			fmt.Println("EVENT BEFORE SCENARIO:", name)
		}
	})
}
```

That is not probably a pleasant thing to integrate, but it is also hard to determinate what exactly we should do when there are empty scenarios or features, whether hooks should still be called or not. Maybe they should not, I will need to have a look at other cucumber implementations to make this decision

**Comment by l3pp4rd** [comment]
updated to properly skip feature events if empty or if all scenarios are empty. since that is more sensible option. Should work as expected now

**Comment by agajdosi** [comment]
@l3pp4rd Thank you for answer. I am a little bit lost in it right now, but tomorrow will try out the new release of Godog and your suggestions and will let you know later.
