### ISSUE TITLE
Mocking DB in godog tests

### ISSUE THREAD

**Issue by demamoh** [DATA-DOG/godog#108]
Are there any examples out there to mock db for faster godog tests?

**Comment by l3pp4rd** [comment]
Hi, since **godog** is BDD testing framework, in general your tests should be integration tests and it is better to use a real database, for that I would suggest using  https://github.com/DATA-DOG/go-txdb which basically isolates all your database calls within transaction. When you start your godog test suite, it should prepare general database structure, then each scenario would run within transaction (which will make your tests execute very fast). On each scenario you should prepare some context in database necessary, then make an action and assert the outcome. There is an example using **tx-db** https://github.com/DATA-DOG/godog/tree/master/examples/db

If you have a NoSQL database, then before each scenario you should clean the database manually.

https://github.com/DATA-DOG/go-sqlmock is meant for unit tests and that will not reflect your real database behavior.

**Comment by demamoh** [comment]
Thanks for the resources. To add, do you know of an easy tool to load fixture data into the database?

**Comment by l3pp4rd** [comment]
for integration tests using tx-db, your database should reflect initial production like database, like for example you may have some product order statuses loaded in db., but not product or categories. These should be created for each scenario like:

``` gherkin
Scenario: put product in basket
  Given in store there is "Lightsaber" for 5.9€ in "Toys" category
  When I put "Lightsaber" in my basket
  Then my basket total should be 5.9€
```

You should load the initial database structure the same way you do it for production, usually some migration tool. For such I personally use a custom utility, but there are plenty of RDMS migration tools out there.

In general you do not need fixtures, all you need for your scenarios are few items to test the behavior.
