### ISSUE TITLE
coverage data with godog

### ISSUE THREAD

**Issue by montera82** [DATA-DOG/godog#112]
just like go test where i could do `go test -coverprofile=coverage.txt`

any ideas how this could be achieved with godog ?

i.e something like
`godog --coverprofile=coverage.txt`

basically i need to output some kind of coverage data with `godog`

**Comment by l3pp4rd** [comment]
Hi, you need to integrate godog with go test and run your tests as usual with `go test` the coverage will work as expected. see how to configure it in [readme](https://github.com/DATA-DOG/godog#running-godog-with-go-test), the godog command is optional, but it will still work with go test integration

**Comment by montera82** [comment]
thanks @l3pp4rd , 
i setup TestMain in root file as follows:

file ./main_test.go
``` go
package mapper

import (
	"github.com/DATA-DOG/godog"
	"github.com/mycompany/mapper/config"
	b "github.com/mycompany/mapper/features/bootstrap"
	log "github.com/sirupsen/logrus"
	"testing"
	"os"
)

var (
	URL = "http://localhost"
)

func TestMain(m *testing.M) {
	status := godog.RunWithOptions("godog", func(s *godog.Suite) {
		conf, err := config.LoadEnv()
		if err != nil {
			log.Fatal(err)
		}

		b.FeatureContext(s, URL)
		b.RecipesContext(s, conf.BrokerDSN)

	}, godog.Options{
		Format: "pretty",
	})

	if st := m.Run(); st > status {
		status = st
	}

	os.Exit(status)
}
```

and then when i run 

``` bash
/go/src/github.com/mycompany/mapper # go test -covermode=atomic -coverprofile=cover.txt main_test.go 
ok      command-line-arguments  0.502s  coverage: 0.0% of statements [no tests to run]

```
and i get an empty cover.txt file created with content `mode: atomic`

even though i noticed it ran the godog tests i have in features/* folder, why does it say [no tests to run] and why do i have no reasonable coverage data in cover.txt ?

**Comment by l3pp4rd** [comment]
why do you specify main_test.go as an argument? `go test -covermode=atomic -coverprofile=cover.txt main_test.go` run it with: `go test -covermode=atomic -coverprofile=cover.txt` if I run it in godog library it properly shows the coverage, maybe you have another TestMain function somewhere? what go version?

**Comment by montera82** [comment]
i tried with
`go test -covermode=atomic -coverprofile=cover.txt`
eventhough in stdin, i see the runing of godog  tests , it still does not record any coverage to cover.txt
only thing in the .txt file is a line with text `mode: atomic` 

confirmed only one TestMain func in the project...
``` bash
/go/src/github.com/mycompany/mapper # go version
go version go1.8.3 linux/amd64

```

**Comment by montera82** [comment]
also see my env...(btw i am running inside docker)

``` bash
LOG_LEVEL=debug
DEBUG=true
HOSTNAME=e6c97f5907ac
SHLVL=1
HOME=/root
PORT=80
STATSD_DSN=noop://
SERVICE_NAME=mapper
TERM=xterm
PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
APP_DIR=/go/src/github.com/mycompany/mapper
GOPATH=/go
PWD=/go/src/github.com/mycompany/mapper
GOLANG_VERSION=1.8.3

```

**Comment by l3pp4rd** [comment]
indeed, this is interesting, haven't seen such issue before, could you print the layout of your project, maybe the tests are run in different package apart from what is being tested and that way it does not detect any coverage on tested package, since go test treats the current package for coverage

**Comment by montera82** [comment]
this is the directory content of `/go/src/github.com/mycompany/mapper`

```
  ── cmd
│   ├── api
│   └── consumer
├── config
├── domain
├── errors
├── features
│   └── bootstrap
├── infrastructure
└── vendor
 
```

**Comment by l3pp4rd** [comment]
The reason why you do not get any coverage, is because you test packages outside the scope of the package you run tests. Even, if you replace godog tests with standard go tests, you will get the same zero coverage.

The test command should be run in the package you test in order to get coverage. since in your step definitions, you include other packages to test their public interface, you get zero coverage, since that package is imported, but is not the current package you start `go test` in. Do you understand the reason?

In golang everything is based per package, see the issue https://github.com/golang/go/issues/6909
So far I think there are tools, to calculate imported package coverage, but that is not so far a built in go command feature.

**Comment by montera82** [comment]
hi @l3pp4rd 
indeed this is happening because my project has its steps definition defined in another package i.ie in `features/bootstrap`, and thus importing the packages in `cmd/*` 
also looking more closely in [godog docs](https://github.com/DATA-DOG/godog/tree/master/examples/api), i could see that `_test.go` is appended to the end of the step definition files which i was not doing.

Now i'll try to refactor my project accordingly so that i get the coverage metrics from my godog tests.
i read how the guys at [elastic search](https://www.elastic.co/blog/code-coverage-for-your-golang-system-tests) did some thing nearly related ( although they used an internal built testing tool) ..

thanks!

**Comment by l3pp4rd** [comment]
regarding step definitions, it is fine to import it. you do not need to refactor it. since you import step definitions in test.go file it will never be a part of test coverage. the reason why you do not have test coverage is that you import the packages where your actual source code is, which you are testing.
If you run go test from inside that package where your source code is then it will be included in coverage.
