### ISSUE TITLE
Failed scenario outlines does not appear in the final resume

### ISSUE THREAD

**Issue by agajdosi** [DATA-DOG/godog#113]
This is a request for a small feature. When Godog test run ends, it prints out all failed scenarios, however scenario outlines are missing. It can be a little bit confusing when one executes longer sets of features or reads logs of nightly tests and is used to only check the resume of the test run - many failures can be missed that way. For example, when one scenario fails and one scenario outline also, one can miss the second in the log.

Would be nice to have outlines failures printed out in the resume.

**Comment by l3pp4rd** [comment]
Hi, you mean the failed outline example is not there in the summary? if that is so, then this is like a bug, I'll check later some cases. maybe you could share a screenshot?

**Comment by l3pp4rd** [comment]
![2018-01-10-103857](https://user-images.githubusercontent.com/132389/34763183-e5f55836-f5f2-11e7-87d3-4eda82968444.png)

So given this example: 5 steps fail (5 scenarios and one in outline). the output for pretty format, I agree is  confusing, since you do not see error messages and scenario headlines. probably this could be unified to be same for console output based formatters and be similar to progress format, but additionally have the scenario headline

**Comment by agajdosi** [comment]
Hi @l3pp4rd, thanks for reply. I have forgot to mention we are using pretty format. Using latest release, version 0.7.4 I am getting the same result as you:
![screenshot from 2018-01-10 12-39-50](https://user-images.githubusercontent.com/22000268/34771052-755f017e-f603-11e7-9683-d43e04e0bb1c.png)

**Comment by l3pp4rd** [comment]
![2018-03-04-103612](https://user-images.githubusercontent.com/132389/36943784-e03a26d2-1f97-11e8-9ca0-450655a0417d.png)

**Comment by l3pp4rd** [comment]
I think I'll still apply one more change, now the references to `test.feature:10` for example points to step in feature, but it could point to scenario so you could easily rerun only that scenario: `godog test.feature:8` (since actual scenario is on line 8, we can use it from error output to copy, paste and rerun that scenario)

**Comment by agajdosi** [comment]
> it could point to scenario so you could easily rerun only that scenario

@l3pp4rd Sounds good. Thank you for the fix, will give it a try soon.
