### ISSUE TITLE
Comments on steps are taken as part of the step definition

### ISSUE THREAD

**Issue by agajdosi** [DATA-DOG/godog#127]
I would like to be able to comment single step, for example to note, that it should be removed if specific bug is fixed or for other reasons. I would like to do:

```
When deleting minishift home directory "test" succeeds #some comment
``` 
However when I run it, the Godog takes the command as part of the step text:

```
  Scenario: User is able to retrieve host and port of OpenShift registry                                                                        # features/test.feature:5
    When file from "https://raw.githubusercontent.com/minishift/minishift/master/addons/anyuid/anyuid.addon" is downloaded into location "test" # testsuite.go:741 -> /testsuite.downloadFileIntoLocation
    When deleting minishift home directory "test" succeeds #some comment
    Then minishift home directory "test" shouldn't exist                                                                                        # testsuite.go:232 -> *Minishift./testsuite.minishiftHomeDirectoryShouldntExist

1 scenarios (1 undefined)
3 steps (1 passed, 1 undefined, 1 skipped)
705.542383ms

You can implement step definitions for undefined steps with these snippets:

func deletingMinishiftHomeDirectorySucceedsSomeComment(arg1 string) error {
        return godog.ErrPending
}

func FeatureContext(s *godog.Suite) {
        s.Step(`^deleting minishift home directory "([^"]*)" succeeds #some comment$`, deletingMinishiftHomeDirectorySucceedsSomeComment)
}
```

**Comment by l3pp4rd** [comment]
Hi, **godog** uses [gherkin language](https://github.com/cucumber/cucumber/wiki/Gherkin) by cucumber.io which is developed and maintained in cucumber organization. Gherkin only allows full line comments and I think it is reasonable. Your scenarios and steps should describe it well enough, if not, scenario can be additionally commented in full line comments. In my own opinion, it would be even hard to maintain those comments, usually they soon become misleading, if you change the code and in most cases forget to update the comment properly.

In your specific use case, I would tag the scenario `@flacky` or just leave it as godog.ErrPending instead of allowing it to pass (and hopping to fix it later for whatever reasons)

**Comment by agajdosi** [comment]
@l3pp4rd Thank you for clarification, missed the fact that it might be due to gherkin specs. Will consider your tips and find most suitable option available. Closing the issue now.
