### ISSUE TITLE
How to skip scenario in the program? Or how to dynamically add tags in the program?

### ISSUE THREAD

**Issue by zeromike** [DATA-DOG/godog#132]
Due to the logic of previous code, we have to check whether we need to skip the test during the program. But I didn't find anyway to skip the scenario during the program. The only way I know is to add tags before program begin, but in my case, I have to do that during the program. Any way to do that?

**Comment by l3pp4rd** [comment]
Hi, at the moment, there is no other option apart from tags or some static context, where in step definition you would return `godog.ErrUndefined` or `godog.ErrPending` which would cause to treat the step as pending implementation or undefined. Though, in order to know in the step function whether to skip that scenario steps, you would need to use BeforeScenario hook and store the flag somewhere in order to skip the steps based on that.

There is a plan to make it much better, see #88 if hooks could return an error, then you could skip those scenarios right in BeforeScenario hook.

**Comment by marc0der** [comment]
It would be great if it was possible to ignore Features or Scenarios driven by the Gherkin itself through tags. It doesn't feel right to hide vital inclusion/exclusion information from stakeholders by placing it in the step defs.

How feasible is it to provide something similar to `@CucumberOptions` where a `~` tag can be provided to exclude certain tagged features/scenarios?

In other words, mark the scenario:

    @wip
    Scenario: This scenario is ignored

and run with:

    $ go test --godog.tags=~wip

or:

    var opt = godog.Options{Output: colors.Colored(os.Stdout), Tags: "~wip"}

in configuration.

**Comment by l3pp4rd** [comment]
hi @marc0der the cli options work normally for tagged scenario filters. (apart from outline examples #133)
I think the question was more about scenario skipping from code itself.

So for example when errors will be supported as return values in hooks, see #88 then we could return `godog.ErrUndefined` for example to skip the scenario from code in general in before scenario hook.

**Comment by marc0der** [comment]
@l3pp4rd thanks for clarifying that. I just ran up a small test project and it does indeed work as expected. Sorry for the confusion :-)
