### ISSUE TITLE
Stop godog from parsing Scenario Outline example data table

### ISSUE THREAD

**Issue by iamthadiyan** [DATA-DOG/godog#151]
I am not sure if this is intended to be so, but I am confused by the behavior.

When I have the following Scenario Outline:

>   Scenario Outline: outline1
>     Given url <endpoint>
>     And query parameters <query_params>
>     When method <method>
>     Then status is <status>
>     Examples:
>       | method | endpoint   | query_params | status |
>       | GET    | /endpoint1 | ?a=1&b=1     | 200    |
>       | GET    | /endpoint1 | ?a=1&b=1&c=3 | 200    |

I see the following snippet generated. 

> func FeatureContext(s *godog.Suite) {
>         **s.Step(`^query parameters \?a=(\d+)&b=(\d+)$`, queryParametersAB)**
>         s.Step(`^method GET$`, methodGET)
>         **s.Step(`^query parameters \?a=(\d+)&b=(\d+)&c=(\d+)$`, queryParametersABC)**
> }

My question is on the text in bold. Why is godog parsing this text? This is a little different from cucumber gherkin parsing. 

One side effect of this is that if I have 100 lines in the data table, I am forced to implement all of them. 

Is there a way I can ask godog to not do this parsing?

**Comment by l3pp4rd** [comment]
Hi, might be a bug in that case, will try to have a look in 12h, thanks for reporting

**Comment by l3pp4rd** [comment]
OK, this is not a bug, the reason, why you struggle is that godog translated all outline scenario steps first, by replacing parameters from Examples. then tries to match it with defines steps. The reason why it does not match, is your regular expression for this step. I suggest to quote it or change regexp to:

``` go
s.Step(`^query parameters ([^$]+)$`, queryParameters)
```

This one would match that query string argument.
Otherwise, the better option is to quote it:

``` gherkin
  Scenario Outline: outline1
    Given query parameters "<query_params>"
```

Then the godog should suggest a regexp like this for step definition:

``` go
s.Step(`^query parameters "([^"]*)"$`, queryParameters)
```

What you need to understand, is that all step definitions are matched with a regular expression, which groups are translated into parameters for the step.

Close it, if you do not have other questions

**Comment by iamthadiyan** [comment]
Ah! I see :) Thanks for your investigation. I am closing it.

Excellent work with GODOG, by the way.

**Comment by l3pp4rd** [comment]
thanks, hope you will enjoy it ;)
