### ISSUE TITLE
Work with test files inside features/steps

### ISSUE THREAD

**Issue by mec07** [DATA-DOG/godog#165]
In order to keep repos neat and tidy and to maintain consistency with similar programs `cucumber` (ruby) and `behave` (python) it would be great to be able to put the godog steps into `features/steps`, so that we have a folder structure like this:
```
features
├── activity.feature
└── steps
    └── activity_test.go
```

This is a "nice to have" feature. Thanks!

**Comment by l3pp4rd** [comment]
hi @mec07 godog works like `go test` it can only process test files which are in the current root directory when you run it. it is not a bug and rather an expected behavior. when for instance you run `go test ./...` it would build each directory test suite and run it separately. You cannot import other package tests that is the restriction and isolation in go toolchain.

**Comment by mec07** [comment]
Thanks for clarifying that @l3pp4rd !
