### ISSUE TITLE
Order Scenery Execution

### ISSUE THREAD

**Issue by inluxc** [DATA-DOG/godog#166]
Is there an way that we can order the scenary execution, when i do an Sanity or Regression tests and there is a lot of scenaries involved, can we order the execution?

**Comment by l3pp4rd** [comment]
Hi, godog accepts arguments as feature files, you can order them with unix command tools such as **find** in feature files itself all scenarios by default are run in order, unless **random** option is used.

Though, it is not advisable or good practice to stick with order, since in such case you will not prevent unexpected state failures. Each scenario should run in isolation
