### ISSUE TITLE
How can we go about templatizing features files?

### ISSUE THREAD

**Issue by kargakis** [DATA-DOG/godog#170]
```
godog client.feature.tmpl
```
The above command does not work because `godog` only expects files with a `.feature` extension. We need to templatize features files in order to enable running the same set of godog tests across environments (eg. we want to use different dns names depending on where the tests are actually running). 

My idea was to always work on a template when we develop a feature, then generate the actual features file based on the env and use that to run the tests. I guess the hard part with the above proposal is that by allowing files with any name to be used as features, the generation of the golang filename is complicated?

**Comment by l3pp4rd** [comment]
Hi, I can make a change for such cases to imply that the given arguments which are files, would be expected to be feature files no matter the extension. but the directories would still be scanned for files with `.feature` extension. If you would have these files located in directories, you'd need to run `godog $(find some/dir -name '.tmpl') so that files would be passed as arguments. Does it make sense?

**Comment by kargakis** [comment]
@l3pp4rd yes, that makes sense. This is the minimum change we need 👍
