### ISSUE TITLE
Add `--init`-flag to `godog` to initialize a go project with `godog`

### ISSUE THREAD

**Issue by dg-ratiodata** [DATA-DOG/godog#27]
# Current Situation

There's no easy way to setup a (new) project with `godog`.

# Proposed Change

It would be nice to have a `--init`-flag like we have on `cucumber-ruby` to setup a (new) project with cucumber-godog.

~~~bash
godog --init
~~~

**Comment by l3pp4rd** [comment]
hm, in general, that could create only a **features** directory. I would not like to enforce anything else to users. though, extending command like tool with too many options would start to get confusing, which are  important and useful and which are not. I do not want to add too many features, especially those which does not make much and are too simple to setup. like configuration files with tags and directory layouts..

**Comment by dg-ratiodata** [comment]
That's what is created in `cucumber-ruby`:

~~~
% cucumber --init
create   features
create   features/step_definitions
create   features/support
create   features/support/env.rb
~~~

**Comment by l3pp4rd** [comment]
in go, you put step definitions in standard **_test.go** files, because you might reuse some test functions or helper utilities. Another issue, is that the step definitions **must** go in the same package (root) directory, otherwise they won't be compiled.

godog runs only per single package and it makes sense. In future it may run and compile separate packages as suites. But for now, the **init** command can be simply pronounced to `mkdir features`
