### ISSUE TITLE
Test position when running in concurrency

### ISSUE THREAD

**Issue by Dogild** [DATA-DOG/godog#63]
Hi, 

When launching the test in concurrency, we don't know in which position the test is in the queue.

This kind of feature is for instance used in parallel_test (https://github.com/grosser/parallel_tests) with the env variable TEST_ENV_NUMBER. This is slightly difference though, in parallel this information is set in a environment variable as different processes are launched. In godog it would more linked to the Suite I guess. 

Do you think it's a good idea to add that in Godog, or would you prefer that the testers take care about that ?

Thanks,

**Comment by l3pp4rd** [comment]
if you want to run it in different databases concurrently, run godog command in a wrapper with a specific env parameters for feature groups you like. you can take a look at [beflash](https://github.com/DATA-DOG/beflash) which was used only for the reason that php does not support concurrency, go does support it. I really do not care how you will use godog in what kinds of contexts, but I will not put such features inside it, it does not make any sense and it is sad that you think it does. do you understand that these kinds of features are based on your context? how would you maintain such a feature for various contexts? why at all it needs to be there, if it only fits 30% use cases? It would confuse users, because if you program well enough, your program can run concurrently, same must your test suite. and these are the most of the use cases.

**Comment by Dogild** [comment]
You're right!

**Comment by kamal-github** [comment]
Maybe out of topic, By default, Go dog tests and scenario run sequential or parallel?

**Comment by l3pp4rd** [comment]
@kamal-github sequential. only `progress` formatter is now capable to run with a concurrency level option. In the future probably other formatters apart from `pretty` will support concurrency option. but for that, I need to refactor some parts of code.
