### ISSUE TITLE
Preffered way to pass some test context between steps?

### ISSUE THREAD

**Issue by mogthesprog** [DATA-DOG/godog#69]
Hi,

I'm currently working on building some tests for an authenticating proxy, and i'm a bit stuck about how to pass results between stages of the test. At the moment i'm using a sort of "feature" struct, which i'm populating and consuming information from, is this the "idiomatic" way? Or is there some way i'm unaware of? 

For instance, I want to test my implementationg of the OAUTH2 flow, so there's a lot of 

```
    Scenario: A Request made                                                                                            
        Given an upstream server that pings                                                                             
        And an ADFS server that is preauthenticated                                                                     
        And a client                                                                                                    
        When I start a proxy server configured for the ADFS server                                                      
        And I request /Index.html from the proxy server                                                                 
        Then I should be redirected to the ADFS login URL                                                               
        When I follow the redirect                                                                                      
        Then I should be redirected to the callback URL with a query parameter                                          
        When I follow the redirect                                                                                      
        Then I should be redirected to the original page (relative URL)                                                 
        Then I should get an OK response with index.html in the body          
```

Is there some internal godog context? Any help or guidance would be really appreciated. Thanks

**Comment by l3pp4rd** [comment]
Hi,

You can take a look at [api example](https://github.com/DATA-DOG/godog/tree/master/examples/api) to see how the state is transferred and reset within steps.

The good practice is to have a `struct` like:

``` go
type suite struct {
    state int // any state within scenario. can be database connection and etc
}
```

Then, you can define steps on suite, so you can access the state:

``` go
func (s *suite) thereAreGodogs(available int) error {
	s.state = available
	return nil
}
```

And finally register steps and hook to reset the state before each scenario so it could start fresh.

``` go
func SuiteContext(s *godog.Suite) {
	c := &suite{}
        s.Step(`^there are (\d+) godogs$`, c.thereAreGodogs)

	s.BeforeScenario(func(interface{}) {
	        c.state = 0 // clean the state before every scenario
	})
}
```

In your case, state is different, but you should get the concept. you should have a OAuth server started and listening, on some port with some configuration options for that scenario in order to authenticate or not.

Well, your step definitions are hardly understandable for non developers.
Your steps should be readable and understandable to users who would use that behavior. So if your web application requires user to sign in through OAuth, he should not know or be aware what redirection happens or what OAuth server is available. All he knows is that he sees a form, where for example he can sign in through github or facebook.

I haven't worked much with OAuth. but all the redirection and requests to OAuth server should be happening in **one step** because user sees only one action - **to sign in** and that is one click.

``` gherkin
Scenario: sign in with facebook account                                                                                           
        Given a registered user "john.doe@my-site.com"
        When John attempts to sign in
        Then he should see the "Home Page"                                                                                                
```

These steps are clear even to product owner.

- step 1. stores a valid account in your suite state, so OAuth server could authenticate it. it could save it to database if your OAuth server reads authentication rules from there in order to authorize. If your account domain model, requires more fields, simply generate them, password, address and etc, because in this context only authentication matters.
- step 2.  So when a **SignIN** button is clicked a lot of stuff happens behind the step definition of yours, you ping your OAuth server and validate, return an error if that fails. You build your OAuth request and preauthenticate user **John** which you match by name and email based on your conventions in the steps. So since this user was added to authorization rules, it matches him and authenticates and redirects to **Home Page** (not index.html) which is hardly understandable to the reader of your steps. 
- step 3. You simply assert that HTML produced by response, has some text which identifies that user is on page after successful authentication. 

Hope you get the point, the things I have listed might not be exactly what you should implement, but the general point is, that steps should be short and simple and orthogonal, so they could be reused through your test suite all over. There may be many actions behind one step.

For example if you develop a web API. your user is a developer, so he should be able to use and integrate the API and understand the step definitions. In this case, your user is a web page user and not a developer.

**Comment by mogthesprog** [comment]
This is an awesome response! Thank you for taking the time to write it.

I had actually implemented something similar to what you had done above, then found myself adding more and more fields the the "state" struct, and couldn't help but feel there's a better way to do it. 

It's good to know that i was on track with it. 

On your steps comment, you've just set a :bulb: off in my head about BDD. I'm pretty new to this, and really appreciate the feedback. I'll restructure the way i do it and hopefully have a better time of it.

Thanks!

**Comment by mogthesprog** [comment]
Also, this is by far the simplest to use BDD implementation in Go. :+1:

**Comment by l3pp4rd** [comment]
glad you are finding it useful ;)

**Comment by mogthesprog** [comment]
haha I am! The other implementations (ginkgo, goconvey) make heavy use of closures.... and it makes for really ugly code with lots of brackets. It takes some of the fun out of go for me to be honest.

**Comment by l3pp4rd** [comment]
yes, and though, there is no concept of steps, which in cucumber can be reused in any scenarios. it is all about steps, making them orthogonal and composable.
