### ISSUE TITLE
Calling Steps from Step Definitions - Public API ?

### ISSUE THREAD

**Issue by Dogild** [DATA-DOG/godog#73]
Hi, 

Right now, we can call a step from a step definitions by calling the go method, for instance :
```golang
func (c *CukeRest) TheRequestShouldBeSuccessful(mode string) error {
	if mode == "creation" {
		return c.TheRequestShouldBeSuccessfulWithTheResponseCode(mode, 201)
	}

	return c.TheRequestShouldBeSuccessfulWithTheResponseCode(mode, 200)
}

// TheRequestShouldBeSuccessfulWithTheResponseCode checks if the last request was successful with the given code and mode
func (c *CukeRest) TheRequestShouldBeSuccessfulWithTheResponseCode(mode string, code int) error {
...
}
```

However, by doing in this way, the hooks `BeforeStep` and `AfterStep` will not be called. 
Is it something we could considerate for godog ?

Thanks,

**Comment by l3pp4rd** [comment]
Hi, I do not see nothing wrong with that, hooks are triggered based per gherkin steps only and if you call steps from other steps that is still **one** step in gherkin. Adding such magic in core library, would be confusing and I would certainly avoid it.

By calling a step from another step you make it one step and treat it like that.

**Comment by Dogild** [comment]
I'm not sure to understand this sentence : "hooks are triggered based per gherkin steps only and if you call steps from other steps that is still one step in gherkin". The and is a && or more like a but ?

**Comment by l3pp4rd** [comment]
Well, I meant that the step in gherkin is not the same as step definition in your code. You can proxy step definition functions through another function, which would trigger your own after and before step hooks if you wish to have such behavior.

**Comment by Dogild** [comment]
Ok! You prefer to do it manually than from godog then!

**Comment by l3pp4rd** [comment]
No, I think there is no magic way first of all in golang, to invoke such hooks, when you would call a step definition func directly in code. That would require a step definition to return a list of steps or their function references in code. like:

``` go
func multiStep() error {
     step1 := func() error {
          return myStep1("arg1", "arg2")
     }
     step2 := func() error {
          return myStep2("arg1")
     }
     return godog.MagicError(step1, step2)
}
```

Does this look nice, not confusing and meaningful? other option a list of step strings, so it could be parsed and matched to a step definition. It would be ugly and confusing in my opinion, I saw some cucumber implementations, which did this for a while, not sure if there are better, less ugly ways. But I most likely would stick to the current behavior even if you could find an elegant solution, because it does not look intuitive.

**Comment by Dogild** [comment]
It looks nice, it how we do it here!

I know it would be not intuitive since you would have two ways to call a same step.  
I have a use case where something should be before every steps (called by godog or called by another steps), it's why I was thinking about this kind of solution.

Thanks

**Comment by mroth** [comment]
> other option a list of step strings, so it could be parsed and matched to a step definition. It would be ugly and confusing in my opinion, I saw some cucumber implementations, which did this for a while, not sure if there are better, less ugly ways.

I believe you mean something such as this syntax: https://github.com/cucumber/cucumber/wiki/Calling-Steps-from-Step-Definitions

e.g. patterns such as their first example on that page:

```ruby
Given /^the user (.*) exists$/ do |name|
  # ...
end

Given /^I log in as (.*)$/ do |name|
  # ...
end

Given /^(.*) is logged in$/ do |name|
  step "the user #{name} exists"
  step "I log in as #{name}"
end
```

I use this pattern _very_ frequently in Ruby version of Cucumber, and find it incredibly helpful to build up a simple library of easily understandable scenarios out of re-usable components. I would love to make a feature request for something similar in godog, which I believe is different from the original request OP made in this issue, but since this is something @l3pp4rd mentioned I'm putting it in this thread instead of opening a new issue.

My assumption is a godog version could look something like:
```go
fun isLoggedIn(name string) (err error) {
    err = s.SubStep(fmt.Sprintf("the user %s exists", name))
    err = s.SubStep(fmt.Sprintf("I log in as %s", name))
    return
}

func FeatureContext(s *godog.Suite) {
    s.Step(`^(.*) is logged in$`, isLoggedIn)
}
```
I believe this would allow for error propagation while maintaining a simple structure.

(However, my expectation would be that the BeforeStep/AfterStep would only fire once, since as @l3pp4rd put it, this is being "used as" a single step.)

Thoughts?

**Comment by l3pp4rd** [comment]
Hi @mroth I would agree to add this feature, if we could find a nice elegant way to implement this.

In your suggestion **s** refers to **godog.Suite** as far as I understand, which may not be available in step, unless the reference is carried within context. It makes it not as straight forward as I would expect as an user.

Our [step function](https://github.com/DATA-DOG/godog/blob/master/suite.go#L78) is an interface{} and validated when registered. If we would extend this step registration function, we could accept:

``` go
fun isLoggedIn(name string) []string {
   return []string{
      fmt.Sprintf("the user %s exists", name),
      fmt.Sprintf("I log in as %s", name),
   }
}

func FeatureContext(s *godog.Suite) {
    // ...previous steps
    s.Step(`^(.*) is logged in$`, isLoggedIn)
}
```

Though, that would add some internal complexity, managing this. Guess that is much more obvious to an user and I would prefer that over the suggested strategy.

Also, it should manage undefined, when one of these combined steps is undefined. The error propagation should be obvious.

**Comment by mroth** [comment]
Good catch on the missing Suite handle in the context.

I really like your suggestion on simplifying the user API to this!

I suppose in order to manage it then, the handler would end up doing reflection on the type of return value it gets -- returning itself as results on `error/nil`, and recursing into sub patterns if it sees `[]string`? Is that correct understanding?

It might be also be possible to wrap `[]string` as a specific type for convenience, which would then make the API look _very_ similar to the Ruby version, which has step(string) / steps(array) shortcuts for this purpose.

```go
type step string
type steps []string
/* ...possible convenience/util methods for step/steps */

fun isLoggedIn(name string) steps {
    return steps{
      fmt.Sprintf("the user %s exists", name),
      fmt.Sprintf("I log in as %s", name),
    }
}
```

Not sure if that's desirable of it it's too much abstraction however.

**Comment by l3pp4rd** [comment]
>> I suppose in order to manage it then, the handler would end up doing reflection on the type of return value it gets -- returning itself as results on error/nil, and recursing into sub patterns if it sees []string? Is that correct understanding?

Yes, we would use reflect to determine whether it is an `error` or `[]string` in return value. And build the **godog.StepDef** accordingly.

When we register a step with `Suite.Step` it creates a `godog.StepDef`, we will need to add an additional field `[]string as steps` to that step definition struct, so when it is matched from gherkin AST, we could match those multi steps and execute them, including the calls to before and after step hooks.

**Comment by l3pp4rd** [comment]
I have created the [multistep branch](https://github.com/DATA-DOG/godog/tree/multistep) as an experiment. But I really do not like the idea, because:

1. if we run step hooks (before, after) for a substep, what would be the **gherkin.Step** for the hook? that would require to build the gherkin step from text given or use the parent step. Which leads to options.
2. We cannot send the substep to formatter, because it may print it or interpret in custom different ways.
3. If we just execute the substeps, then it looses the point and in the end it is the same as calling steps from the source code.

**Comment by mroth** [comment]
I hear you on the implementation complexities and tradeoffs.  Ultimately, it's certainly up to you whether you want to bear that cost in your project for this feature!

For background, I figured it might be helpful to your decision to explain in more detail how I envision this being used, based on how I've used it personally in Ruby Cucumber, some past projects, as well as a library for Godog I have been experimenting with.

The place I see this used most often is in setup ("Given") steps. FWIW in my past experience, I actually didn't expect to see the substeps in the formatter, nor would it have been desirable to see them in my use cases (the Ruby Cucumber implementation also does not display them in the pretty formatter).  Also in my use case, failure conditions in the substeps are rare [although certainly not impossible], since they are usually "setup" conditions used across a wide variety of scenarios.

To give you a simple example from the [lolcommits](https://github.com/mroth/lolcommits) project I worked on a long time ago:
```ruby
require 'aruba/cucumber'

Given(/^a git repo named "(.*?)"$/) do |repo_name|
  steps %(
    Given I successfully run `git init --quiet "#{repo_name}"`
  )
end

Given(/^I am in a git repo named "(.*?)"$/) do |repo|
  steps %(
    Given a git repo named "#{repo}"
    And I cd to "#{repo}"
  )
end

Given(/^I am in a git repo named "(.*?)" with lolcommits enabled$/) do |repo|
  steps %(
    Given I am in a git repo named "#{repo}"
    And I successfully run `lolcommits --enable`
  )
end
```
In this case, _these steps are being composed and made up entirely using substeps of steps defined by an external library_ ([Aruba](https://github.com/cucumber/aruba), which provides Cucumber steps for testing command line operations -- e.g. the `I successfully run...` and whatnot which seem simple but are actually fairly complex under the hood, when you start to think about things like capturing/testing different output pipes and exit codes, handling different environments/OSes, etc)

It was trivially easy to compose these steps, and of course they end up getting re-used in many ways quite a bit across the project.  The ease of writing/using those compound steps ended up being the major factor in using Aruba/Cucumber for integration testing on the project (and made it much easier to ask open-source contributors sending PRs to attempt to write corresponding integration tests for their features).  The combination of Cucumber/Aruba in this way is so useful that I use it on projects written in other languages as well, for example my [scmpuff](https://mroth.github.io/scmpuff/) project requires Ruby for integration testing for this reason despite being written in Go, and GitHub's popular [hub](https://github.com/github/hub) is another Go project that does the same.

Using Aruba steps as my example here is intentional: as *I'm actually in the process of experimenting with writing on an open-source library very similar to Aruba but for Godog instead of Ruby Cucumber* (nothing public yet). E.g. a combination of an API for isolated fs/system operations along with a series of well defined Godog steps. This way a user could easily import and use to write integration tests with Godog for command line apps written in any language. (Sidenote: the key distinction from Aruba being the one I am writing is intended to be highly concurrent safe and with more reliable cross-platform support, as well as run in environments without dependencies).

I imagine an audience for this library are will include people writing these steps who might not be experienced Go programmers (or even Go programmers at all). When they need to do something slightly more complex than possible with the default steps I provide, based on my past experiences with Aruba I believe that being able to re-compose my steps in this fashion would be significantly more desirable than trying to duplicate all the functionality via directly interacting with the low-level API.

Of course, my desires only speak for myself, so take them with a grain of salt!

**Comment by l3pp4rd** [comment]
Well, thanks for explaining it in such detail. If we do not need hooks to be fired for each sub-step or sub-sub-step. Then this can be integrated without any trade offs or usage confusion.

``` gherkin
Scenario: multistep
  Given multistep
```
From gherkin perspective godog can treat it as a single step, but from inner step implementation, many nested steps may be involved, executed in sequential order:

- the first nested undefined step, results in undefined gherkin step. (though, will need to manage the undefined step snippet properly)
- the first nested step error, results in gherkin step error.
- the first nested skipped step, results in skipped gherkin step.

The reason, why I mentioned the hook issue, is because this issue was opened for a reason that there should be separate hooks fired for nested steps. Since I see that, there is no clean way to fire those hooks, because in general there is a single gherkin step.

But for the concept of simple nested step definition - I agree, this can have a clean integration and will be useful. I will continue with that branch, you can track the progress and keep a discussion.

By the way, I haven't used aruba, but it is great to hear about evolving BDD in go language in such ways.
Let me know when you have something interesting to share ;)

**Comment by mroth** [comment]
> Let me know when you have something interesting to share ;)

Will do! It's a side project from a side project, so I don't have too much time to work on it right now, but I'm _hoping_ to have a very rough working proof of concept in a few weeks.
