### ISSUE TITLE
Summary method called at the beginning of the test ?

### ISSUE THREAD

**Issue by Dogild** [DATA-DOG/godog#74]
Hi, 

The interface `Formatter` provides the method `Summary` called at the end of the tests. It could be great to print a Summary before the tests are launched as well; method who could take in parameter the features of which will be launched.

This would imply to break current formatters, any other idea to do that ?
Thanks,

**Comment by Dogild** [comment]
I have added in my fork a new method `Agenda(fs []*gherkin.Feature)` called at the beginning of the test. Let me know if you would be interested by

**Comment by l3pp4rd** [comment]
There is some development going on in [core gherkin language](https://github.com/cucumber/gherkin-go) right now, currently godog uses version 3. but some time later it will be 5 and current formatters might change their interface (up until V1 of godog is released). I think godog will start using some extra features of gherkin pickles and that might change the formatter interface, I'm not aware yet whether it will be able to know all features it is going to run in order to support such a feature like agenda. Since now it is not necessary, I will delay it up until v1 is released (which will finalize the formatter interface at some point).

**Comment by l3pp4rd** [comment]
this will not be integrated in core. you may use BeforeSuite hook
