### ISSUE TITLE
Concurrency of scenarios within feature

### ISSUE THREAD

**Issue by mroth** [DATA-DOG/godog#75]
Presently it appears the concurrency support in godog functions by running `N` Feature suites concurrently.  However, the Scenarios within a given Feature are run in sequence. Thus, a test suite that consists of a small amount of `.feature` files but a large amount of scenarios will not benefit from increased concurrency in the godog settings.

My understandings:
  1. Scenarios that wish to benefit from concurrency _should_ already be written in a way that they are concurrency safe and do not rely on global variables (and the godog documentation already warns about this and provides several examples of doing it properly).
  2. From looking at a quick informal survey of `*.feature` files around the internet, it seems that it is quite common for cucumber test suites to have a large number of scenarios per feature, and a smaller number of overall feature files. 

I can assert that my own scenarios tend to be _highly_ beneficial from concurrency (they tend to involve some degree of latency from IO), and being able to parallelize with concurrency across a single `.feature` would greatly increase test speeds (I verified this experiment by writing a script to put each scenario in its own feature file -- this is of course unmaintainable for a real test suite, but allowed me to see speed impact).

I would like to request consideration around making the concurrency setting apply at Scenario level granularity, versus Feature level.  Or am I missing something here?

Thanks!

**Comment by l3pp4rd** [comment]
Yes it makes sense, I was already thinking about it. But it is a little bit tricky with the **BeforeFeature** and **AfterFeature** hooks. Should this be sequential? because if we call those concurrently it could end up like:

1. BeforeFeature a.feature
2. BeforeFeature c.feature
3. AfterFeature c.feature
4. BeforeFeature b.feature ...

Not sure, whether this could lead to some backward incompatible misbehavior. Though, it could be explained in detail, how it behaves when running concurrently. If the test suite is implemented well, again that should not impact users.

Gherkin 5 will have pickles and events available in the library. I might make some refactoring based on these later to formatters. It would be much more convenient to run them concurrently instead of what godog does now - an outline is not split into separate scenarios at the moment. Plus, pretty formatter might be more simple using pickles.

Not sure, yet whether this should go first before pickle integration. Currently the scenario outline would be run sequentially if we would change concurrency from feature level to scenario at the moment. I would prefer to split it per pickle.

**Comment by mroth** [comment]
> But it is a little bit tricky with the BeforeFeature and AfterFeature hooks. Should this be sequential? because if we call those concurrently it could end up like:
>
>1. BeforeFeature a.feature
>2. BeforeFeature c.feature
>3. AfterFeature c.feature
>4. BeforeFeature b.feature ...
>
> Not sure, whether this could lead to some backward incompatible misbehavior.

Does this not already happen in master when Features are run with concurrency?  That was my expectation from looking at the code, but I may have been mistaken.

Either way, as it would only affect things when concurrency was specifically enabled, and documentation specifically instructs people to make Contexts concurrency safe if they intend to use the concurrency feature, it probably shouldn't cause significant regression. 

(As long as things don't end up such that `AfterFeature a.feature` somehow runs prior to `BeforeFeature a.feature` or anything like that, of course!)

> Gherkin 5 will have pickles and events available in the library. I might make some refactoring based on these later to formatters. It would be much more convenient to run them concurrently instead of what godog does now - an outline is not split into separate scenarios at the moment. Plus, pretty formatter might be more simple using pickles.
>
> Not sure, yet whether this should go first before pickle integration. Currently the scenario outline would be run sequentially if we would change concurrency from feature level to scenario at the moment. I would prefer to split it per pickle.

This sounds interesting! Is there any documentation on the Gherkin 5 / pickles? Haven't been able to find much via searching. Also agree that if this is coming soon it may make sense to wait and deal with being able to refactor things in the ideal way.

**Comment by l3pp4rd** [comment]
Hi @mroth see the #97 there is a trade off I need to make regarding this scenario level isolation. And I tend to keep the concurrency level at feature, because it will leave the flexibility for users to choose the isolation level on scenario or feature state. The reason to have feature level isolation is due to time it takes to reload the state:

- spin up a VM
- ssh somewhere
- prepare database state and so on..

It will still allow user to have a flexibility to fully isolate scenario context and using before scenario hook, for example reload the whole suite context. Though, it will not force users to maintain best practices and isolate scenario state.
