### ISSUE TITLE
Selenium WebDriver

### ISSUE THREAD

**Issue by llonchj** [DATA-DOG/godog#77]
Hi,

I am using godog with selenium to test browser interaction. In order to access webdriver I use something like:

```go
type WebDriver struct {
	selenium.WebDriver
}

func (w *WebDriver) iAmAnAnonymousUser() error {
	return w.DeleteAllCookies()
}

func FeatureContext(s *godog.Suite) {
	wd, err := NewBrowser()
	if err != nil {
		panic(err)
	}

	s.Step(`^I am a anonymous user$`, wd.iAmAnAnonymousUser)

	s.AfterSuite(func() {
		wd.Quit()
		wd = nil
	})
}
```

In this scenario, only a browser/webdriver (wd) instance is allowed per suite. 

I would like to use concurrency using a different webdriver instance on each feature. What will be the best practice?

**Comment by l3pp4rd** [comment]
Hi, I haven't used selenium yet with godog. But from what I understand, it would be wise to have a pool of WebDrivers and on each BeforeFeature hook, you take one from the pool and put it back to pool in AfterFeature hook.

Here is a very basic [sync.Pool](https://golang.org/pkg/sync/#example_Pool) usage example:

``` go
var objPool = sync.Pool{
	New: func() interface{} {
		return NewObject()
	},
}

p := objPool.Get().(*Object)
// use p
objPool.Put(p)
```

So instead of NewObject you make `NewBrowser`. The pool will automatically allocate a new browser if there isn't one available in the pool.

**Comment by llonchj** [comment]
Thanks for your answer, @l3pp4rd 

How can I access then the right browser object from a Step function?

**Comment by l3pp4rd** [comment]
The best practice is to have a suite context with all the state in a separate structs, which has all the steps as functions bind to that struct.

``` go
package main

import (
	"fmt"
	"sync"
	"time"

	"github.com/DATA-DOG/godog"
)

type selenium int64 // just to simulate selenium instance

var pool = sync.Pool{
	New: func() interface{} {
		return selenium(time.Now().UnixNano()) // should create NewBrowser
	},
}

type webContext struct {
	wd selenium
}

func (c *webContext) passingStep() error {
	fmt.Println("using browser:", c.wd)
	return nil
}

func FeatureContext(s *godog.Suite) {
	context := &webContext{}

	s.Step(`^passing step$`, context.passingStep)

	s.BeforeScenario(func(interface{}) {
		context.wd = pool.Get().(selenium)
	})
	s.AfterScenario(func(interface{}, error) {
		pool.Put(context.wd)
	})
}
```

I used a simple **selenium** type in order to show you, that it is a different reference.

![2017-04-27-114613](https://cloud.githubusercontent.com/assets/132389/25475438/68cf8c6a-2b3f-11e7-9022-f95837b00b8a.png)

You can see in the screenshot what are the results when running concurrently. There is no **BeforeFeature** hook though, forgot about it. But Before and After scenario are good hooks for this kind of task, since you should isolate global state for each scenario.

**Comment by llonchj** [comment]
@l3pp4rd Thank you! I am not using a pool to avoid inherit browser state. It worked!
