### ISSUE TITLE
Command option for different sort option of the feature

### ISSUE THREAD

**Issue by Dogild** [DATA-DOG/godog#78]
Hi, 

Right now the features are launched in order based on their path ( type `featuresSortedByPath`)
It would be interesting to have more options than just the path (this one could be by default). For instance we could want to launch the features where there are the more scenarios or steps. 

This could be the option `-s --sort [path, min_steps, max_steps, min_scenarios, max_scenarios]` for instance. 

One of the use case would be to launch the test with the most steps at the beginning (when  launching test in concurrency), so we don't end up with a long alone test running at the end of the suite for instance.

Let me know what you think ? 

Thanks,

**Comment by l3pp4rd** [comment]
hm, maybe I'll just remove this sorting and let you do the magic by sorting them anyway you like. because it would execute them in order you give paths: 

1. `godog a.feature b.feature d.feature c.feature`
2. `godog $(find . -name '*.feature' | sort)`

There are hundreds of ways you can sort your features (I will never integrate such a thing in the library itself) because these are not orthogonal features and there are two many variants, which are mostly available from unix commands. It also allows to create scripts and aliases for custom sorting and stuff.
