### ISSUE TITLE
Not possible to use DocString and Datatable with multistep definition

### ISSUE THREAD

**Issue by Dogild** [DATA-DOG/godog#89]
Hi, 

Right now, godog does not allow to use `gherkin.DocString` and `gherkin.DataTable` with a multisteps definition.
For instance this piece of code will not work:

```cucumber
Then I launch the following steps:
""" 
*the container @centos is running
*the container @nginx is running
"""
```

```go
s.Step(`^I launch the following steps:$`,func () ILaunchTheFollowingSteps(d *gherkin.DocString) godog.Steps {
 	steps := strings.Split(d.Content, "*")[1:]
 
 	for i, s := range steps {
 		steps[i] = strings.TrimRight(s, "\n")
 	}
 
 	return godog.Steps(steps)
 })
```

Godog will complain that the function `ILaunchTheFollowingSteps` expects one argument.

One possible way to fix this issue is to modify the method `maybeUndefined` :

```go
func (s *Suite) maybeUndefined(step *gherkin.Step, text string) (undefined []string) {

	def := s.matchStepText(text)

	if nil == def {
		undefined = append(undefined, text)
		return
	}

	if !def.nested {
		return
	}
        
        // This has been added
	if def != nil && step.Argument != nil {
		def.args = append(def.args, step.Argument)
	}

	for _, next := range def.run().(Steps) {
		undefined = append(undefined, s.maybeUndefined(nil, next)...)
	}

	return
}
```

Another issue is the substeps can not have any `gherkin.DocString` or `gherkin.Datatable`.
For instance this will not work (as the step.Argument is different to the args of the `StepDef`):

```cucumber
Then I launch the following steps:
""" 
*I launch a container and tag it as @centos with the options:
    | type          | docker|
    | image        | centos |
    | labels        | name=centos1 |
"""
```

**Comment by l3pp4rd** [comment]
right, good point, thanks @Dogild 

We cannot support multi line nested steps, the reason is that, they do not come from a gherkin.Step definition parsed from a feature file.
In order to support such a feature, we would need to match and parse argument as a table or content body. But gherkin parser does not provide such a feature so far, to parse some other gherkin node apart from feature file itself. I'm not sure when I may have a look at gherkin parser for such a task, it may be lot of refactoring there.

Anyway, concerning the step argument, when step is inspected for undefined nested steps, this is fixed, we now pass an argument.
Currently it will produce an error when a nested step is multi line. Later we may parse it using gherkin parser if that change will be feasible. 

Leaving it is a low priority task, but something to be as a remainder later.

**Comment by l3pp4rd** [comment]
closing, nested steps will not be allowed to have DocString or DataTable arguments, solution would be too ugly

**Comment by kruczekrobert** [comment]
I'm currently working on a normal solution. I'm waiting for the Gherkin side to fix it first, then I'll move on to this one.
https://github.com/cucumber/gherkin/pull/592
