### ISSUE TITLE
Coverage with running godog with go test ?

### ISSUE THREAD

**Issue by AlexandreRzc** [DATA-DOG/godog#91]
Hi

Is it possible to get the coverage running godog with go test ?
I tried with the sample, the tests were executed but got a warning and a 0.0% in coverage

-----------------------

/go/src/github.com/DATA-DOG/godog/examples/godogs# go test -v -cover
... 3

1 scenarios (1 passed)
3 steps (3 passed)
356.725µs

Randomized with seed: 1497605524518706237
testing: warning: no tests to run
PASS
coverage: 0.0% of statements

**Comment by l3pp4rd** [comment]
well, maybe you need to have at least one go test, because godog currently takes into account all coverage when run with `go test`

**Comment by AlexandreRzc** [comment]
hmm i tried the official example in 
https://github.com/DATA-DOG/godog/tree/master/examples/godogs

it should work if i understand ? anyone has the same problem ?

**Comment by l3pp4rd** [comment]
it has no standard go tests, try godog itself:
```
cd $GOPATH/github.com/DATA-DOG/godog
go test -cover
go test -v -cover
``` 

You should see different coverage percentage, because -v runs different formatter which is not widely covered with unit tests.

What I mentioned in the first message, is that you must have at least one standard go test func in order to have coverage report.
