### ISSUE TITLE
Add BeforeFeature() and AfterFeature() methods

### ISSUE THREAD

**Issue by agajdosi** [DATA-DOG/godog#97]
Hi, I would like to propose or ask for a new feature. It would be superb for me to be able to register functions which will be executed before or after each feature. I did some research and if I am not mistaken it seems that there is currently no possibility to implement this behaviour with Godog. The only mention is in #75 but here it seems just like a theoretical play with BeforeFeature().

I am working on Minishift project, which provisions a VM and thus is quite state dependent. It would be nice for me if I would be able to do a full clean up after each feature, not only after whole suite.

Is it possible to run functions before and after Features, or could be this implemented?

**Comment by l3pp4rd** [comment]
Hi, currently godog runs feature by feature even concurrently the unit is feature. It would support such a hook before and after feature and your state might be safe. But in the future there are plans to have concurrency level at single scenario, which would break the feature level isolation.

In terms of best practices, it makes sense to isolate everything to a single scenario, so it would not depend on previous scenario run or feature scope. If I would implement these (before and after feature) hooks now and later shift concurrency level to scenario, there may be BC breaks for many users and these hooks would not make any sense anymore.

So in general, this feature request depends on the question - whether it is better to have concurrency level at scenario and force users to isolate their state and context to scenario level, or leave the current behavior and add these (before and after feature) hooks.

In such cases as yours, in order to highly reduce the suite execution time, it totally makes sense to switch to feature level state isolation, even if it brings some risks in terms of state affecting other scenarios. And current implementation of concurrency at feature level, allows users to choose whether to isolate at feature or scenario level. But isolation at scenario in current implementation does not allow to run scenarios from separate features concurrently, which may actually be depending on feature level state and you would not be able to test that dependency breakage.

So I have to make and document a trade off here regarding this isolation level. But guess it is a better option to be more practical and allow users to choose whether to hold the state in feature context or not.
I'll think about it for some time and will add these hooks most likely.

**Comment by agajdosi** [comment]
@l3pp4rd Thank you for amazing insight into the current and planned situation around Godog.

> But guess it is a better option to be more practical and allow users to choose whether to hold the state in feature context or not.

I think that having both options, if that is possible, would be best solution. I can imagine projects like Minishift which requires spinning up VM, or other kind of time consuming need before the actual product is "usable". And for these having features as basic units is question of saving time. Also this is practical when one wants to create a user story based test.

But I also understand that for some projects or their parts having scenario as basic unit is the thing. For UI testing I guess this could be just great.

Being able to isolate on both levels could make it harder to understand, but it is common if one adds versatility.

Looking forward how you will resolve this, thanks for great project.

**Comment by l3pp4rd** [comment]
Thanks, it is already resolved and hooks before and after feature were added, users can choose their level of isolation, whether it will be scenario or feature, by flushing and preparing state after one or another.

**Comment by agajdosi** [comment]
@l3pp4rd Looking forward to use it, thank you.
